<?php

namespace IM\SysTurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
    public function findAllByCriteria($texto) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT c from IMSysTurBundle:Cliente c
        WHERE c.fechaBaja IS NULL
        AND (c.apellido LIKE :texto1
        OR c.nombres LIKE :texto2
        )');
        $query->setParameter('texto1', '%'.$texto.'%');
        $query->setParameter('texto2', '%'.$texto.'%');
        $clientes = $query->getResult();

        return $clientes;
    }
    
    public function findAllActive() {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT c from IMSysTurBundle:Cliente c '
                . 'WHERE c.fechaBaja IS NULL');
        $clientes = $query->getResult();
        
        return $clientes;
    }
    
    public function getDocumentos($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT d FROM IMSysTurBundle:Documento d '
                . 'WHERE d.fechaBaja IS NULL '
                . 'AND d.cliente = :id');
        
        $query->setParameter('id', $id);
        
        $documentos = $query->getResult();
        
        return $documentos;
    }
    
    public function getContactos($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT c FROM IMSysTurBundle:Contacto c '
                . 'WHERE c.fechaBaja IS NULL '
                . 'AND c.cliente = :id');
        
        $query->setParameter('id', $id);
        
        $contactos = $query->getResult();
        
        return $contactos;
    }
}
