<?php

namespace IM\SysTurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteFileRepository extends EntityRepository
{
    public function getOneByClienteFile($idfile, $idcliente) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT cf from IMSysTurBundle:ClienteFile cf '
            . 'WHERE cf.cliente = :idcliente '
            . 'AND cf.file = :idfile');

        $query->setParameter('idcliente', $idcliente);
        $query->setParameter('idfile', $idfile);
        $clientexfile = $query->getSingleResult();

        return $clientexfile;
    }
}
