<?php

namespace IM\SysTurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoRepository extends EntityRepository
{
}
