<?php

namespace IM\SysTurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
    public function findAllByCriteria($texto) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT f from IMSysTurBundle:File f, IMSysTurBundle:ClienteFile cf, IMSysTurBundle:Cliente c
        WHERE f.id=cf.file AND cf.cliente = c.id
        AND f.fechaBaja IS NULL
        AND (
          f.nombre LIKE :texto1
          OR c.apellido LIKE :texto2
          OR c.nombres LIKE :texto3
          OR c.dni LIKE :texto4
        )');
        $query->setParameter('texto1', '%'.$texto.'%');
        $query->setParameter('texto2', '%'.$texto.'%');
        $query->setParameter('texto3', '%'.$texto.'%');
        $query->setParameter('texto4', '%'.$texto.'%');
        $files = $query->getResult();

        return $files;
    }

    public function findAllActive() {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT f from IMSysTurBundle:File f '
            . 'WHERE f.fechaBaja IS NULL');
        $files = $query->getResult();

        return $files;
    }

}
